T2_DIARS/Controllers/PokemonsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using T2_DIARS.Models;

namespace T2_DIARS.Controllers
{
   
    public class PokemonsController : BaseController
    {
        private readonly AppPruebaContext context;
        private readonly IHostEnvironment _hostEnv;
        private readonly IConfiguration configuration;

        public PokemonsController(AppPruebaContext context, IHostEnvironment hostEnv, IConfiguration configuration) : base(context)
        {
            this.context = context;
            this.configuration = configuration;
            _hostEnv = hostEnv;
        }
        public ActionResult Pokemon(string search)
        {

            var pokemones = context.Tipos.ToList();

            ViewBag.Buscar = search;
            var pokemon = context.Pokemones
                .Include(o => o.Tipo)
                .ToList();

            if (!string.IsNullOrEmpty(search))
            {
                pokemon = pokemon.Where(s => s.Nombre.Contains(search)).ToList();
                return View("Pokemon", pokemon);
            }
            return View("Pokemon", pokemon);
        }
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Tipos = context.Tipos.ToList();
            return View("Create", new Pokemons());
        }
        [Authorize]
        [HttpPost]
        public ActionResult Create(Pokemons pokemones, IFormFile image, string nombre)
        {
            if (image != null && image.Length > 0)
            {
                var basePath = _hostEnv.ContentRootPath + @"\wwwroot";
                var ruta = @"\Pokemones\" + image.FileName;
                using (var strem = new FileStream(basePath + ruta, FileMode.Create))
                {
                    image.CopyTo(strem);
                    pokemones.Imagen = ruta;
                }
            }
            else
            {
                ModelState.AddModelError("Image", "Este campo es obligatorio");
            }
            var pokemons = context.Pokemones.ToList();
            foreach (var item in pokemons)
            {
                if (item.Nombre == nombre)
                {
                    ModelState.AddModelError("NombreV", "Pokemon Existente");
                }
            }
            Console.WriteLine("Imagen? " + image);
            if (ModelState.IsValid)
            {
                context.Pokemones.Add(pokemones);
                context.SaveChanges();
                return RedirectToAction("Pokemon");
            }
            else
            {
                ViewBag.Tipos = context.Tipos.ToList();
                return View("Create", pokemones);
            }
        }
        public string imagen()
        {
            return _hostEnv.ContentRootPath + @"\wwwroot";
        }
    }
}

T2_DIARS/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using T2_DIARS.Controllers;
using T2_DIARS.Models;

namespace T2_DIARS.Controllers
{
    public class UserController : BaseController
    {
        private readonly AppPruebaContext context;
        private readonly IConfiguration configuration;
        public IHostEnvironment hostEnv;

        public UserController(AppPruebaContext context, IHostEnvironment hostEnv, IConfiguration configuration) : base(context)
        {
            this.context = context;
            this.configuration = configuration;
            this.hostEnv = hostEnv;
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View("Login");
        }
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            var user = context.Users
                .Where(o => o.Username == username && o.Password == CreateHash(password))
                .FirstOrDefault();
            //validar si el usuario existe, y si el password es correcto
            if (user != null)
            {
                var claims = new List<Claim> {
                    new Claim(ClaimTypes.Name, username)
                };

                var claimsIdentity = new ClaimsIdentity(claims, "Login");
                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                HttpContext.SignInAsync(claimsPrincipal);

                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("Login", "Usuario o contraseña incorrectos.");
            return View();
        }
        [HttpGet]
        public ActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return View("Login");
        }
        private string CreateHash(string input)
        {
            var sha = SHA256.Create();
            input += configuration.GetValue<string>("Token");
            var hash = sha.ComputeHash(Encoding.Default.GetBytes(input));

            return Convert.ToBase64String(hash);
        }
        [HttpGet]
        public ActionResult Registrar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Registrar(User user, string password, string passwordConf)
        {
            if (password != passwordConf) 
                ModelState.AddModelError("PasswordConf", "Las contraseñas no coinciden");

            if (ModelState.IsValid)
            {
                user.Password = CreateHash(password);
                context.Users.Add(user);
                context.SaveChanges();
                return RedirectToAction("Login");
            }
            return View("Registrar", user);
        }
    }
}

T2_DIARS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - T2_DIARS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">T2_DIARS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pokemons" asp-action="Pokemon">Pokemons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Registrar">Registrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - T2_DIARS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>